name: harvest_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.0
  path_provider: ^2.1.2
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7
  url_launcher: ^6.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.png
    - assets/harvester_icon.png
    - assets/harvester_icon_2.png
    - assets/DP_thaya.jpeg
