// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe38_dFJjGCgldPFMRXS9KAoaQ_YKuJ9k',
    appId: '1:41447259559:web:a17cf1d52018fe93400a82',
    messagingSenderId: '41447259559',
    projectId: 'harvestbuddy-f0314',
    authDomain: 'harvestbuddy-f0314.firebaseapp.com',
    storageBucket: 'harvestbuddy-f0314.appspot.com',
    measurementId: 'G-3REP1RCW73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR2vYMwlqrXonUL6yJbet2hNj1sQJGxGs',
    appId: '1:41447259559:android:3dbbde3d188564c6400a82',
    messagingSenderId: '41447259559',
    projectId: 'harvestbuddy-f0314',
    storageBucket: 'harvestbuddy-f0314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkx6LZTMI4S4TzlKdYi8QSjSxp3zf0AsI',
    appId: '1:41447259559:ios:07712f78ddfe9bed400a82',
    messagingSenderId: '41447259559',
    projectId: 'harvestbuddy-f0314',
    storageBucket: 'harvestbuddy-f0314.appspot.com',
    iosBundleId: 'com.example.harvestBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkx6LZTMI4S4TzlKdYi8QSjSxp3zf0AsI',
    appId: '1:41447259559:ios:0d582b354933089f400a82',
    messagingSenderId: '41447259559',
    projectId: 'harvestbuddy-f0314',
    storageBucket: 'harvestbuddy-f0314.appspot.com',
    iosBundleId: 'com.example.harvestBuddy.RunnerTests',
  );
}
